// client-vue/src/components/Categories.vue
<template>
  <div class="container CategoriesComponent">
    <div class="container ContentPart">
      <div class="ContentPart__form">
        <h1 class="form__element">{{selectedCategoryIndex!==null ? categories[selectedCategoryIndex].name : 'Новая категория'}}</h1>
        <input type="text" class="form__element form__textbox" placeholder="Название" v-model="filledName">
        <input type="text" class="form__element form__textbox" placeholder="Ссылка" v-model="filledLink">
        <textarea cols="30" rows="10" class="form__element form__textbox form__textarea" placeholder="Описание" v-model="filledDescription"></textarea>
        <button v-if="selectedCategoryIndex!==null" class="form__element form__button form__button-delete" @click="OnDeleteButtonClick">Удалить</button>
        <button class="form__element form__button" @click="OnSaveButonClick">Сохранить</button>
      </div>
    </div>
    <ul class="container Sidebar Categories">
      <li class="Sidebar__li"><button class="Sidebar__button Sidebar__icon" @click="OnCategorySelection(null)"><i class="far fa-plus-square"></i></button></li>
      <li class="Sidebar__li" :key="category._id" v-for="(category, index) in categories"><button class="Sidebar__button" @click="OnCategorySelection(index)">{{category.name}}</button></li>
    </ul>
  </div>
</template>

<script>
import Sidebar from './Subcomponents/Sidebar';
import AXIOS from '../axios-common';

export default {
  name:'categories',
  data () {
    return {
      selectedCategoryIndex: null,
      filledName: null,
      filledLink: null,
      filledDescription: null,
      filledId: null
    }
  },
  components: {
    Sidebar
  },
  methods: {
    OnCategorySelection (index) {
      if(index!==null){
        this.selectedCategoryIndex = index;
        this.filledName = this.categories[index].name;
        this.filledLink = this.categories[index].link;
        this.filledDescription = this.categories[index].description;
        this.filledId = this.categories[index]._id;
      }else{
        this.selectedCategoryIndex = null;
        this.filledName = null;
        this.filledLink = null;
        this.filledDescription = null;
        this.filledId = null;
      }
      
    },
    OnSaveButonClick () {
      let requestString = '/admin/setcategory';
      if(this.selectedCategoryIndex===null){
        requestString = '/admin/newcategory';
      }

      // HERE SOME PROBLEMS
      AXIOS.post(requestString,{
          name: this.filledName,
          link: this.filledLink,
          description: this.filledDescription,
          _id: this.filledId
        })
        .then( (result)=>{
          console.log(result);
          this.$store.commit('updateCategories',result.data);

          this.selectedCategoryIndex = result.data.length-1;
          this.filledName = result.data[this.selectedCategoryIndex].name;
          this.filledLink = result.data[this.selectedCategoryIndex].link;
          this.filledDescription = result.data[this.selectedCategoryIndex].description;
          this.filledId = result.data[this.selectedCategoryIndex]._id;
        })
        .catch( (error)=>{
          console.log('Error with POST to '+requestString);
          console.log(error);
        })
    },
    OnDeleteButtonClick () {
      AXIOS.post('/admin/delcategory',{
        _id: this.filledId
      })
      .then( (result)=>{
        console.log(result);
        this.$store.commit('updateCategories',result.data);

        this.selectedCategoryIndex = null;
        this.filledName = null;
        this.filledLink = null;
        this.filledDescription = null;
        this.filledId = null;
      })
      .catch( (error)=>{
        console.log('Error with POST from delete category ');
      });
    }
  },
  
  computed: {
    categories: function () {
      return this.$store.state.Categories;
    }
  },
  beforeCreate () {
    if(!this.$store.state.key){
      this.$router.go('/login');
      console.log("Key NOT exists");
      return;
    }
    console.log("Key exists");
  }
}
</script>

<style scoped>
.CategoriesComponent{
  width: 82%;
  height: 100%;
}
.ContentPart{
  width: 80%;
  height: 100%;
  flex-wrap: wrap;
}
.Categories{
  width: 20%;
  height: 100%;
}
.ContentPart__form{
  width: 650px;
  min-height: 500px;
  border-radius: 2px;
  background: rgb(228, 228, 228);
  padding: 30px;
}
.form__element{
  margin: 10px 0;
}
.form__textbox{
  font-size: 20px;
  width: 90%;
  padding: 5px 10px;
}
.form__textbox:focus{
  outline-color: teal;
}
.form__textarea{
  text-align: left;
  padding: 10px;
  resize: none;
}
.form__textarea::placeholder{
  text-align: center;
}
.Sidebar__icon{
  font-size: 30px;
  color: teal;
}
.form__button{
  width: 40%;
  font-size: 20px;
  padding: 8px 10px;
  margin-left: 10px;
  margin-right: 10px;
}
.form__button-delete{
  background: rgb(233, 71, 71);
  box-shadow: 7px 7px 2px rgb(163, 52, 52);
}
.form__button-delete:active{
  box-shadow: 3px 3px 2px rgb(163, 52, 52);
}
</style>

// client-react/src/Components/Categories/Categories.js
import React, { Component } from "react";
import "./Categories.css";

import axios from "axios";

import Sidebar from "../Sidebar/Sidebar";

class Categories extends Component{
  state = {
    categories: null,
    selectedCategory: {
      name: "Новая категория",
      link: "",
      description: ""
    },
    selectedIndex: null,
    nextNew: true
  }
  OnNameInput = (event) => {
    this.setState({
      selectedCategory: {
        ...this.state.selectedCategory,
        name: event.target.value
      }
    });
  }
  OnLinkInput = (event) => {
    this.setState({
      selectedCategory: {
        ...this.state.selectedCategory,
        link: event.target.value
      }
    });
  }
  OnDescriptionInput = (event) => {
    this.setState({
      selectedCategory: {
        ...this.state.selectedCategory,
        description: event.target.value
      }
    });
  }

  componentWillMount = () => {
    // Title
    document.title = "Категории";

    // Categories
    axios.get('http://localhost:8080/admin/getcategories', {}).then((result) => {
      this.setState({
        categories: result.data
      });
      console.log(result.data);
    }).catch((error) => {
      alert('Error!');
    });
  }

  OnCategoryClick = (index, e) => {
    console.log(this.state.categories);
    this.setState({
      selectedCategory: this.state.categories[index],
      nextNew: false,
      selectedIndex: index
    });
  }
  OnAddNewClick = () => {
    this.setState({
      nextNew: true,
      selectedCategory: {
        name: "Новая категория",
        link: "",
        description:""
      }
    });
  }

  OnSaveClick = (e) => {
    console.log("70: Started!");
    let requestString = null;
    let requestObj = null;

    if(this.state.nextNew){
      console.log("75: New");
      // Новая категория
      if(this.state.selectedCategory.name!=="" &&
        this.state.selectedCategory.link!=="" &&
        this.state.selectedCategory.description!==""){
          console.log("80: ValidatedNew!");

          requestString = "http://localhost:8080/admin/newcategory";
          requestObj = {
            name: this.state.selectedCategory.name,
            link: this.state.selectedCategory.link,
            description: this.state.selectedCategory.description
          };
          console.log(requestString);
          console.log(requestObj);
        }
      
    }else{
      console.log("93: SetValidated!");
      requestString = "http://localhost:8080/admin/setcategory";
      requestObj = {
        id: this.state.selectedCategory["_id"],
        name: this.state.selectedCategory.name,
        link: this.state.selectedCategory.link,
        description: this.state.selectedCategory.description
      };
      console.log(requestString);
      console.log(requestObj);
    }

    axios.post(requestString, requestObj).then( (result) => {
      console.log(result.data);
      if(result.data.success === true){
        this.setState({
          categories: result.data.categories,
          selectedCategory: {
            name: "Новая категория",
            link: "",
            description: ""
          },
          selectedIndex: null,
          nextNew: true
        });
        console.log("Success! (saving)");
      }
    }).catch( (error) => {
      console.log("Error! (saving)");
    });
  }

  OnDeleteClick = (e) => {
    console.log(this.state.selectedCategory);
    axios.post('http://localhost:8080/admin/delcategory', { id: this.state.categories[this.state.selectedIndex]["_id"] }).then((result) => {
      // {
      //    success: true | false,
      //    categories: []
      // }

      if (result.data.success === true) {
        this.setState({
          categories: result.data.categories,
          selectedCategory: {
            name: "Новая категория",
            link: "",
            description: ""
          },
          selectedIndex: null,
          nextNew: true
        });
      } else {
        alert("Errors with deleting...(in response)");
      }
    }).catch((error) => {
      alert("Errors with deleting...(catch)");
    });

  }

  render(){
    let renderedCategories = null;

    if(this.state.categories){
      renderedCategories = this.state.categories.map( (item,index)=>{
        return (
          <li className="categoriesList__item" key={item.link}>
            <button className="item__button" onClick={this.OnCategoryClick.bind(this,index)}>{item.name}</button>
          </li>
        );
      }); 
    }

    // if(this.state.nextNew){
    //   categoryName = "Новая категория";
    //   categoryLink = "";
    //   categoryDescription = "";
    // }else{
    //   categoryName = this.state.selectedCategory.name;
    //   categoryLink = this.state.selectedCategory.link;
    //   categoryDescription = this.state.selectedCategory.description;
    // }

    return(
      <div className="row wrap">
        <Sidebar></Sidebar>

        <div className="col-md-10">
          <div className="container">
            <div className="row">

              <div className="col-md-4"></div>

              {/* CENTER */}
              <div className="col-md-4 column categoriesColumn">
                <div className="addNewCatBlock">
                  <i class="far fa-plus-square" onClick={this.OnAddNewClick}></i>
                </div>
                <ul className="categoriesList">

                  {renderedCategories}
                  
                </ul>
              </div>

              {/* Change Window */}
              <div className="col-md-4 column">
                <div className="categoriesChange">

                  <p className="categoryLogo" style={this.state.nextNew ? { color: "rgb(8, 160, 160)" } : { color: "#333" } }>
                    {this.state.selectedCategory.name}
                  </p>

                  <label htmlFor="name" className="categoriesChange__label">Название</label>
                  <input type="text" placeholder="Название" id="name" className="categoriesChange__textinput" value={this.state.selectedCategory.name} onInput={this.OnNameInput}/>
                  <label htmlFor="link" className="categoriesChange__label">Ссылка (англ. без пробелов и спец. симв.)</label>
                  <input type="text" placeholder="Ссылка" id="link" className="categoriesChange__textinput" value={this.state.selectedCategory.link} onInput={this.OnLinkInput}/>
                  <label htmlFor="description" className="categoriesChange__label">Краткое описание</label>
                  <textarea id="description" cols="30" rows="10" placeholder="Описание" className="categoriesChange__textinput" value={this.state.selectedCategory.description} onInput={this.OnDescriptionInput}></textarea>
                  <button className="categoriesChange__button delbtn" style={this.state.nextNew ? { display: "none" } : { display: "block" } } onClick={this.OnDeleteClick}>Удалить</button>
                  <button className="categoriesChange__button" onClick={this.OnSaveClick}>Сохранить</button>
                  
                </div>
              </div>

            </div>

          </div>
          
        </div>
      </div>
    );
  }
}

export default Categories;
