// client-react/src/Components/Catalog/Catalog.js
import React, { Component } from "react";
import "./Catalog.css";

import Sidebar from "../Sidebar/Sidebar";
// import NewChangeDataWindow from "./NewChangeDataWindow/NewChangeDataWindow";
import ChangeDataWindow from "./ChangeDataWindow/ChangeDataWindow";
import NewProductWindow from "./NewProductWindow/NewProductWindow";

import axios from "axios";

class Catalog extends Component{
  state = {
    categories: null,
    items: null,
    selectedProduct: null,
    selectedCategory: null,
    newWindow: false
  }

  componentDidMount = () => {
    // Title
    document.title = "Каталог";

    // Categories
    axios.get('http://localhost:8080/admin/getcategories', {} ).then( (result) => {
      this.setState({
        categories: result.data
      });
    }).catch( (error) => {
      alert('Error!');
    });

    axios.post('http://localhost:8080/admin/getcatalog', {
      category: "all"
    }).then((result) => {
      this.setState({
        items: result.data,
        selectedCategory: "all"
      })
    }).catch((error) => {
      alert('Error!');
    });
  }

  OnCategoryClick = (link,name,e) => {
    axios.post('http://localhost:8080/admin/getcatalog', {
      category: link
    }).then( (result) => {
      this.setState({
        items: result.data,
        selectedCategory: link
      })
    }).catch( (error) => {
      alert('Error!');
    });
  }

  OnItemClickChange = (index,e) => {
    
    this.setState({
      selectedProduct: this.state.items[index]
    }); 
  }

  CloseDataWindowMethod = () => {
    this.setState({
      selectedProduct: null
    });
    axios.post('http://localhost:8080/admin/getcatalog', {
      category: this.state.selectedCategory
    }).then((result) => {
      this.setState({
        items: result.data
      })
    }).catch((error) => {
      alert('Error!');
    });
  }

  CloseNewProductWindow = () => {
    this.setState({
      newWindow: false
    });
  }

  AddNewProduct = () => {
    this.setState({
      newWindow: true
    });
  }

  FastProductDelete = (id,e) => {
    axios.post('http://localhost:8080/admin/deleteproduct', {
      id: id
    }).then((result) => {
      if (result.data.success) {

        axios.post('http://localhost:8080/admin/getcatalog', {
          category: this.state.selectedCategory
        }).then((result) => {
          this.setState({
            items: result.data
          })
        }).catch((error) => {
          alert('Error! 1');
        });

      } else {
        alert("Error! 2");
      }
    }).catch((error) => {
      alert("Error! 3");
    });
  }

  render(){
    // console.log(this.state.selectedProduct);
    // console.log("==========");
    // console.log(this.state.selectedCategory);
    let categoriesRendered = null;
    let itemsRendered = null;
    let changeDataWindowRendered = null;
    let newProductWindowRendered = null;

    if(this.state.newWindow){
      newProductWindowRendered = <NewProductWindow
      categories = {
        this.state.categories
      }
      closeMethod = {
        this.CloseNewProductWindow
      }
      />
    }


    if(this.state.categories){
      categoriesRendered =  this.state.categories.map( (item)=>{
        return (
          <li className="catContainer__li" key={item.link}><button className="catContainer__button" onClick={this.OnCategoryClick.bind(this, item.link, item.name)}>{item.name}</button></li>
        );
      });
    }

    if(this.state.items){
      itemsRendered = this.state.items.map( (item,index)=>{
        return (
          <div className="col-md-3 col-sm-4" key={item["_id"]}>
            <div className="card_container">
              <div className="card" style={{ overflow: "hidden" }} >

                <div className="cardmask">
                  <div className="cardmask__wrapper">
                    <i className="fas fa-pencil-alt" onClick={this.OnItemClickChange.bind(this, index)}></i>
                    <i className="fas fa-trash-alt" onClick={this.FastProductDelete.bind(this, item["_id"])}></i>
                  </div>
                </div>

                <img className="card-img-top" src={item.image} alt="Card cap" />
                <div className="card-body">
                  <p className="card-text card__title h5 text-center">{item.name}</p>
                </div>

              </div>
            </div>
          </div>
        );
      });
      
    }

    if(this.state.selectedProduct){
      // changeDataWindowRendered = <ChangeDataWindow item={this.state.selectedProduct} categories={this.state.categories} closeMethod={this.CloseDataWindowMethod} />
      changeDataWindowRendered = <ChangeDataWindow item = {
        this.state.selectedProduct
      }
      categories = {
        this.state.categories
      }
      closeMethod = {
        this.CloseDataWindowMethod
      } 
      selectedCategory = {
        this.state.selectedCategory
      }
      CloseMethod = {
        this.CloseDataWindowMethod
      }
      />
    }

    return(
      <div>
        {changeDataWindowRendered}
        {newProductWindowRendered}
        <div className="row wrap">

          
          <Sidebar></Sidebar>

          <div className="col-md-8">

            <div className="row" style={{ height: "100vh" }} ref={input=>{this.ContentPart = input}}>
              {itemsRendered}
            </div>

          </div>

          <div className="col-md-2 Sidebar">
            <ul className="Sidebar__catContainer">
              <li className="catContainer__li addProductContainer"><i class="far fa-plus-square" onClick={this.AddNewProduct}></i></li>
              <li className="catContainer__li"><button className="catContainer__button" onClick={this.OnCategoryClick.bind(this, "all")}>Весь каталог</button></li>
              {categoriesRendered}
            </ul>
          </div>


        </div>
      </div>
      
    );
  }
}

export default Catalog;

// client-vue/src/components/Catalog.vue
<template>
  <div class="container Catalog">
    <div class="container ContentPart">
      <div class="container ProductCard" :key="product._id" v-for="product in products">
        <div class="container ProductCard__mask">
          <i class="fas fa-pencil-alt mask__icon" @click="OnCardChangeClick(product)"></i>
          <i class="fas fa-trash-alt mask__icon" @click="OnCardDeleteClick(product)"></i>
        </div>
        <div class="container ProductCard__imageContainer">
          <!-- http://www.zoofirma.ru/images/stories/2012/05/17/ryba-sobaka2.jpg -->
          <img v-bind:src="product.image" v-bind:alt="product.name">
        </div>
        <p class="container ProductCard__name">
          {{product.name}}
        </p>
      </div>
    </div>
    <ul class="container Sidebar Categories">
      <li class="Sidebar__li"><button class="Sidebar__button Sidebar__button-icon" @click="OnNewButtonClick"><i class="far fa-plus-square"></i></button></li>
      <li class="Sidebar__li" :key="category._id" v-for="category in categories"><button class="Sidebar__button" @click="OnCategoryClick(category.link)">{{category.name}}</button></li>
    </ul>
  </div>
</template>

<script>
import AXIOS from '../axios-common';

export default {
  name: 'catalog',
  methods: {
    OnNewButtonClick () {
      this.$store.commit('updateChangeWindowType','new');
      this.$store.commit('updateIsChangeWindowOpened', true);
    },
    OnCardDeleteClick (product) {
      AXIOS.post('/admin/deleteproduct', {
      _id: product._id
    })
    .then( (result) => {
      if(result){
        this.$store.commit('updateProducts', result.data);
      }else{
        console.log("Error with POST to DELETE product");
      }
    })
    .catch( (error) => {
      console.log("Error with POST to DELETE product");
    });
    
    },
    OnCardChangeClick (product) {
      this.$store.commit('updateChangeWindowType','edit');
      this.$store.commit('updateChangeWindowProduct', product);
      this.$store.commit('updateIsChangeWindowOpened', true);
    },
    OnCategoryClick (link) {
      AXIOS.post('/admin/getcatalog',{
        category: link
      })
      .then( (results)=>{
        this.$store.commit('updateProducts', results.data);
      })
      .catch( (error)=>{
        console.log("Error with POST /admin/getcatalog");
      })
    }
  },
  computed:{
    categories: function () {
      return this.$store.state.Categories;
    },
    products: function () {
      return this.$store.state.Products;
    }
  }
}
</script>

<style scoped>
.Catalog{
  width: 82%;
  height: 100%;
}
.ContentPart{
  width: 80%;
  height: 100%;
  overflow-y: scroll;
  justify-content: flex-start;
  flex-wrap: wrap;
}
.Categories{
  width: 20%;
  height: 100%;
}

.ProductCard{
  width: 250px;
  height: 300px;
  background: rgb(226, 226, 226);
  margin: 20px;
  position: relative;
  flex-direction: column;
  justify-content: flex-start;
  border-radius: 2px;
  overflow: hidden;
}
.ProductCard__imageContainer{
  max-width: 100%;
  height: 80%;
}
.ProductCard__imageContainer img{
  max-width: 100%;
  height: 100%;
}
.ProductCard__name{
  width: 100%;
  height: 20%;
  font-size: 18px;
}
.ProductCard__mask{
  width: 100%;
  height: 100%;
  position: absolute;
  background: rgba(51, 51, 51, 0.4);
  opacity: 0;
  transition: opacity 150ms linear 0s;
}
.ProductCard:hover .ProductCard__mask{
  opacity: 1;
}
.mask__icon{
  color: #eee;
  font-size: 30px;
  display: block;
  margin: 10px;
  cursor: pointer;
}
.mask__icon:hover{
  color: rgb(192, 192, 192);
}
.Sidebar__button-icon{
  font-size: 30px;
}
.Sidebar__button-icon:active i{
  color: teal;
}
</style>
